name = "moemeter-api"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[triggers]
crons = ["0 3,15 * * *", "*/3 3,15 * * *"]

[observability]
enabled = true
head_sampling_rate = 1
